

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/vue-music-master
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 20MB
      enabled: true
server:
  port: 8081
  servlet:
    session:
      cookie:
        domain: localhost
    context-path: /api


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

